
"""new things added today

Revision ID: 4c305cd2f05c
Revises: 5dae673ad9a8
Create Date: 2025-04-01 12:32:29.821729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c305cd2f05c'
down_revision = '5dae673ad9a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
