
"""Add a new thing

Revision ID: 5756f93e6046
Revises: 90948dbe1fad
Create Date: 2025-03-30 22:13:43.929344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5756f93e6046'
down_revision = '90948dbe1fad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
