
"""Added new things to the table

Revision ID: 5dae673ad9a8
Revises: 5756f93e6046
Create Date: 2025-03-31 11:38:31.204196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dae673ad9a8'
down_revision = '5756f93e6046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_requests', sa.Column('download_url', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('robot_requests', sa.Column('bot_name', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('market', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('stake_amount', sa.Float(), nullable=True))
    op.add_column('robot_requests', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('prediction', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('trading_strategy', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('account_credentials', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('robot_requests', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('robot_requests', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('robot_requests', sa.Column('entry_rules', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('exit_rules', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('risk_management', sa.String(), nullable=True))
    op.add_column('robot_requests', sa.Column('additional_parameters', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot_requests', 'additional_parameters')
    op.drop_column('robot_requests', 'risk_management')
    op.drop_column('robot_requests', 'exit_rules')
    op.drop_column('robot_requests', 'entry_rules')
    op.drop_column('robot_requests', 'take_profit')
    op.drop_column('robot_requests', 'stop_loss')
    op.drop_column('robot_requests', 'order_type')
    op.drop_column('robot_requests', 'volume')
    op.drop_column('robot_requests', 'account_credentials')
    op.drop_column('robot_requests', 'trading_strategy')
    op.drop_column('robot_requests', 'currency')
    op.drop_column('robot_requests', 'prediction')
    op.drop_column('robot_requests', 'duration')
    op.drop_column('robot_requests', 'contract_type')
    op.drop_column('robot_requests', 'stake_amount')
    op.drop_column('robot_requests', 'market')
    op.drop_column('robot_requests', 'bot_name')
    op.drop_column('robot_requests', 'progress')
    op.drop_column('robot_requests', 'download_url')
    # ### end Alembic commands ###
