
"""Add has_requested_robot column to users

Revision ID: 90948dbe1fad
Revises: 333d8e7785c0
Create Date: 2025-03-30 21:41:00.378803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90948dbe1fad'
down_revision = '333d8e7785c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_requests', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('robot_requests', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('robot_requests', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_requested_robot', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('robots_delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'robots_delivered')
    op.drop_column('users', 'has_requested_robot')
    op.drop_column('robot_requests', 'notes')
    op.drop_column('robot_requests', 'delivery_date')
    op.drop_column('robot_requests', 'is_delivered')
    # ### end Alembic commands ###
