
"""new tables

Revision ID: dd5eeef7917f
Revises: deadc07e9e52
Create Date: 2025-04-05 17:16:30.403598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5eeef7917f'
down_revision = 'deadc07e9e52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
