
"""create subscription_plans table

Revision ID: eba42703495c
Revises: 8620c5721456
Create Date: 2025-04-08 13:12:47.758390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba42703495c'
down_revision = '8620c5721456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
